# Generated by Django 4.0.4 on 2022-05-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=str, upload_to=''),
            preserve_default=False,
        ),
    ]
